### PR TITLE
Redesign video page

### PR DESCRIPTION
**Pull request by sethlu**

### CODE REVIEW

**Comment by sethlu** [comment]
Some current progress for feedback

screen shot 2019-01-07 at 2 38 31 am

**Comment by sethlu** [comment]
After a little more redesign

screen shot 2019-01-07 at 3 04 36 pm

**Comment by ajar98** [comment]
Looks amazing!

Kartik's idea of putting the previous and next video buttons on the sides of the video is really good, and if you do that and put the title of the video, and change the "Return to <class>" button into a Back icon, there will be enough space for everything else.

I have some other ideas about reformatting the transcript, but I think we can move that to the next iteration of redesign.

**Comment by Jiuthergeist** [comment]
The full-width design looks great! If possible, maybe we could employ the way YouTube does it - have a theater and a regular mode if we decide to want to keep aspects of the first design you made.

The regular mode (and could maybe be deployed in the theater mode too, although I'm not sure how space would work) may also benefit by displaying all links to all videos in the playlist to allow the user to jump to any video instead of needing to hit next next next.

Also with the suggestion of the side buttons for previous/next videos, those black bars could be buttons to get the next video instead (a button spanning the whole height of the video, if that looks nice?). Maybe just a little left and right arrow respectively within each of these boxes.

We may also need a more obvious button to go back to the class page with the list of all lectures. 

Otherwise this looks much cleaner than what we've had before!

**Comment by KartikKapur** [comment]
Here's a mockup of what I thought the layout could be. Follows pretty closely with yours. Just added a small side bar which could be collapsable. This sidebar would have 2 collapsable tables- one to redirect you to courses and one that shows progress through the lecture/which videos you have to watch.  

Also we could add the x closest lectures (so like another table with 2-3 lectures before and 2-3 lectures after) though I feel this is less important than the other 2 tables.  

Alternatively, if you think it doesn't seem right to have the lecture title in the navbar it could be collapsable on top of the transcript and when the sidebar is opened the title could disappear from the transcript. 

mockup 1

**Comment by ajar98** [comment]
@sethlu I have uploaded a sample playlist for you to play with. As for the video dimensions, I think having it as large as possible is the best option.

**Comment by sethlu** [comment]
Now we've made the chevrons on the sides 🎉 

screen shot 2019-01-17 at 1 18 27 am

And when you hover over it, it becomes just a little lighter

screen shot 2019-01-17 at 1 19 11 am

---

Currently we're only supporting this view mode as default; we'll tweak the design for a full theater view in the near future. The overlay side bar is not yet implemented, and we may perhaps delay it for a future version?

**Comment by KartikKapur** [comment]
This looks awesome!

**Pull request merged**
