### PR TITLE
Home & class page design overhaul

### PR DESCRIPTION
**Pull request by sethlu**
🚧 **DO NOT MERGE**

### CODE REVIEW

**Comment by sethlu** [comment]
**A little bit of design updates** 

screen shot 2018-12-24 at 3 56 34 pm

screen shot 2018-12-24 at 3 56 41 pm

screen shot 2018-12-24 at 3 56 56 pm

**Comment by sethlu** [comment]
**After re-tweaking the designs**

---

Public home page:

screen shot 2018-12-24 at 7 32 02 pm

Home page:

screen shot 2018-12-24 at 7 32 08 pm

Course page:

screen shot 2018-12-24 at 7 32 11 pm

**Comment by ajar98** [comment]
I personally like the teal navbar over white. Also, what does the lectures table look like with actual lectures (and videos underneath)?

**Comment by sethlu** [comment]
@ajar98 

Here's a screenshot from the HermesRevamp course

screen shot 2018-12-26 at 12 48 39 pm

**Comment by sethlu** [comment]
Redesigned the table view for course lectures @ajar98 

screen shot 2018-12-26 at 2 52 28 pm

**Comment by sethlu** [comment]
Brought back the collapsable lecture videos & put the videos in an ordered list @ajar98

screen shot 2018-12-29 at 9 37 30 pm

**Pull request merged**
